; Include file for Top 5 I/O Proces


;Meters

[meterLabelIORead1]
Meter=String
MeterStyle=styleLeftText
X=10
Y=20r
W=190
H=14
Text=I/O Read  #1 [MeasureTopIORead1]

[meterValueIORead1]
Meter=String
MeterStyle=styleRightText
MeasureName=MeasureTopIOReadScaled1
X=200
Y=0r
W=190
H=14
AutoScale=1
NumOfDecimals=1
Text=%1B

[meterLabelIORead2]
Meter=String
MeterStyle=styleLeftText
X=10
Y=20r
W=190
H=14
Text=I/O Read  #2 [MeasureTopIORead2]

[meterValueIORead2]
Meter=String
MeterStyle=styleRightText
MeasureName=MeasureTopIOReadScaled2
X=200
Y=0r
W=190
H=14
AutoScale=1
NumOfDecimals=1
Text=%1B

[meterLabelIORead3]
Meter=String
MeterStyle=styleLeftText
X=10
Y=20r
W=190
H=14
Text=I/O Read  #3 [MeasureTopIORead3]

[meterValueIORead3]
Meter=String
MeterStyle=styleRightText
MeasureName=MeasureTopIOReadScaled3
X=200
Y=0r
W=190
H=14
AutoScale=1
NumOfDecimals=1
Text=%1B


