; Include file for thread

; Measures
[MeterLabelTotalThreads]
Meter=String
MeterStyle=styleLeftText
X=10
Y=140
W=190
H=14
Text=Total Threads

[MeterValueTotalThreads]
Meter=String
MeterStyle=styleRightText
; MeterStyle=styleRightText | styleRightText
X=200
Y=0r
W=190
H=14
Text=[MeasureTotalThreads:0]


; Meters

[MeterLabelTotalThreads]
Meter=String
MeterStyle=styleLeftText
X=10
Y=140
W=190
H=14
Text=Total Threads

[MeterValueTotalThreads]
Meter=String
MeterStyle=styleRightText
; MeterStyle=styleRightText | styleRightText
X=200
Y=0r
W=190
H=14
Text=[MeasureTotalThreads:0]

