; Include file for Top 5 I/O Proces
; @includeMters1=Meters-Top3_IO.inc

; Meters

[meterLabelIORead4]
Meter=String
MeterStyle=styleLeftText
X=10
Y=20r
W=190
H=14
Text=I/O Read  #4 [MeasureTopIORead4]

[meterValueIORead4]
Meter=String
MeterStyle=styleRightText
MeasureName=MeasureTopIOReadScaled4
X=200
Y=0r
W=190
H=14
AutoScale=1
NumOfDecimals=1
Text=%1B

[meterLabelIORead5]
Meter=String
MeterStyle=styleLeftText
X=10
Y=20r
W=190
H=14
Text=I/O Read  #5 [MeasureTopIORead5]

[meterValueIORead5]
Meter=String
MeterStyle=styleRightText
MeasureName=MeasureTopIOReadScaled5
X=200
Y=0r
W=190
H=14
AutoScale=1
NumOfDecimals=1
Text=%1B


[meterLabelIOWrite4]
Meter=String
MeterStyle=styleLeftText
X=10
Y=20r
W=190
H=14
Text=I/O Write  #4 [MeasureTopIOWrite4]

[meterValueIOWrite4]
Meter=String
MeterStyle=styleRightText
MeasureName=MeasureTopIOWriteScaled4
X=200
Y=0r
W=190
H=14
AutoScale=1
NumOfDecimals=1
Text=%1B

[meterLabelIOWrite5]
Meter=String
MeterStyle=styleLeftText
X=10
Y=20r
W=190
H=14
Text=I/O Write  #5 [MeasureTopIOWrite5]

[meterValueIOWrite5]
Meter=String
MeterStyle=styleRightText
MeasureName=MeasureTopIOWriteScaled5
X=200
Y=0r
W=190
H=14
AutoScale=1
NumOfDecimals=1
Text=%1B

