; Include file for Top 5 I/O Proces

;Meters

[meterLabelIOWrite1]
Meter=String
MeterStyle=styleLeftText
X=10
Y=40r
W=190
H=14
Text=I/O Write  #1 [MeasureTopIOWrite1]

[meterValueIOWrite1]
Meter=String
MeterStyle=styleRightText
MeasureName=MeasureTopIOWriteScaled1
X=200
Y=0r
W=190
H=14
AutoScale=1
NumOfDecimals=1
Text=%1B

[meterLabelIOWrite2]
Meter=String
MeterStyle=styleLeftText
X=10
Y=20r
W=190
H=14
Text=I/O Write  #2 [MeasureTopIOWrite2]

[meterValueIOWrite2]
Meter=String
MeterStyle=styleRightText
MeasureName=MeasureTopIOWriteScaled2
X=200
Y=0r
W=190
H=14
AutoScale=1
NumOfDecimals=1
Text=%1B

[meterLabelIOWrite3]
Meter=String
MeterStyle=styleLeftText
X=10
Y=20r
W=190
H=14
Text=I/O Write  #3 [MeasureTopIOWrite3]

[meterValueIOWrite3]
Meter=String
MeterStyle=styleRightText
MeasureName=MeasureTopIOWriteScaled3
X=200
Y=0r
W=190
H=14
AutoScale=1
NumOfDecimals=1
Text=%1B

